services:

  traefik:
      networks:
          - web-public
      ports:
        - "80:80"
        - "443:443"
      deploy:
        update_config:
          parallelism: 1
          delay: 5s
          order: stop-first
        placement:
          constraints:
            - node.role==manager
      volumes:
        # Add Docker as a mounted volume, so that Traefik can read the labels of other services
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - certificates:/certificates
      configs:
        - source: traefik
          target: /etc/traefik/traefik.yml

  php:
    image: example.com/my-repo/my-image:latest # 👈 Be sure to change this to your own image
    networks:
      - web-public
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"
    environment:
      PHP_POOL_NAME: "my-php-app"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.my-php-app.rule=${TRAEFIK_HOST_RULE}"
        - "traefik.http.routers.my-php-app.entrypoints=websecure"
        - "traefik.http.routers.my-php-app.tls=true"
        - "traefik.http.routers.my-php-app.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.my-php-app.loadbalancer.server.port=8080"
        - "traefik.http.services.my-php-app.loadbalancer.server.scheme=http"
        # Health check
        - "traefik.http.services.my-php-app.loadbalancer.healthcheck.path=/ping"
        - "traefik.http.services.my-php-app.loadbalancer.healthcheck.interval=100ms"
        - "traefik.http.services.my-php-app.loadbalancer.healthcheck.timeout=75ms"
        - "traefik.http.services.my-php-app.loadbalancer.healthcheck.scheme=http"

configs:
  traefik:
    name: "traefik.yml"
    file: ./.infrastructure/conf/traefik/prod/traefik.yml

volumes:
  certificates:
  storage_private:
  storage_public:
  storage_sessions:
  storage_logs:

networks:
  web-public:
