---
title: Official Spin Laravel Template
authors:
  - Jay Rogers (@jaydrogers)
repository: https://github.com/serversideup/spin-template-laravel
issues: https://github.com/serversideup/spin-template-laravel/issues